### ISSUE TITLE
support gif and videos for moments

### ISSUE THREAD

**Issue by aytunch** [vanelizarov/flutter_stories#1]

**Comment by vanelizarov** [comment]
@aytunch yeah, I’ve been thinking of it a little while ago, will implement asap. PRs are also highly appreciated 🙂

**Comment by vanelizarov** [comment]
For videos, you can use [video_player](https://pub.dev/packages/video_player) and for GIFs just use the standard `Image` widget, because it supports gifs out of the box. To display any of these you can simply use `momentBuilder` 🙂

**Comment by kyleorin** [comment]
would you mind expanding on this? Tried to do the exact same thing and I end up with `The return type 'VideoPlayerController' isn't a 'Widget', as required by the closure's context.`

Also is there an option to dynamically change between video and photo automatically fetching from firebase?
