### ISSUE TITLE
Minor errors in the package while accessing _currentIdx

### ISSUE THREAD

**Issue by hamza-bilal-gaya** [vanelizarov/flutter_stories#10]
While using the _currentIdx in the package, there is unnecessary usage of not operator(!) which resulted in the error. However, I have copied the whole code and used it as my component and removed all the unnecessary not operator(!) in the code and now the package works totally fine on latest flutter version (2.5.2). Please check it from your side using the latest flutter version, if you want the whole code i'll provide you that.

**Comment by vanelizarov** [comment]
Fix landed in [0.3.1](https://pub.dev/packages/flutter_stories/versions/0.3.1)

**Comment by hamza-bilal-gaya** [comment]
Thanks buddy you have saved the hours many developers by launching this package thanks a lot !😁😁
