### ISSUE TITLE
current index is nullable so it can't be incremented

### ISSUE THREAD

**Issue by Jagmohanrai** [vanelizarov/flutter_stories#8]
I have fixed this issue so should I create a PR  for this?
Anyone with the same problem or it occurs in my project only?

**Comment by Jagmohanrai** [comment]
I have created a PR by fixing this issue

**Comment by vanelizarov** [comment]
Fix landed in [0.3.1](https://pub.dev/packages/flutter_stories/versions/0.3.1)
